### ISSUE TITLE
Should This Repository Be Archived?

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-beginner-workshop#2]

**Comment by jimmychu0807** [comment]
Actually I like this project and think it helps beginners. 

I will vote for the project to "stay". I can take up the maintenance of this project.

**Comment by JoshOrndorff** [comment]
This was most recently used at my Eth Denver workshop back in February. I like this one too, but I won't put up a fight if we want to archive it.

I like that it provides a basic workshop that is mostly ready to go and only needs minimal prep work from the workshop administrator.

**Comment by danforbes** [comment]
If @jimmychu0807 is volunteering to keep up the maintenance I'm happy keeping it. Jimmy, maybe at our next team meeting you can give a little overview of this project and some things we can work on as a team to make sure it stays up-to-date and gets improved and stuff. Could you think about adding some update instructions for this repo on our team Google Doc for Substrate upgrades?

**Comment by jimmychu0807** [comment]
sure. Will do
